version: '3'

services:
  centor-server-4-1:
    image: mrtdeh/kive
    command: --api
    networks:
      - cluster
    environment:
      - NAME=ebrahim
      - DC=dc4
      - PORT=3000
      - SERVER=true
      - LEADER=true
      - ALTERNATIVE_HOST=centor-server-4-1
      - PRIMARIES=centor-server-3-1:3000
    ports:
      - "9994:9090"

  centor-server-4-2:
    image: mrtdeh/kive
    networks:
      - cluster
    environment:
      - NAME=javad
      - DC=dc4
      - PORT=3002
      - SERVER=true
      - JOIN=centor-server-4-1:3000
      - ALTERNATIVE_HOST=centor-server-4-2
      - PRIMARIES=centor-server-3-1:3000
   


  centor-client-4-1:
    image: mrtdeh/kive
    networks:
      - cluster
    environment:
      - NAME=client-4-1
      - DC=dc4
      - PORT=4001
      - JOIN=centor-server-4-1:3000,centor-server-4-2:3002
      - ALTERNATIVE_HOST=centor-client-4-1
    depends_on:
      - centor-server-4-1   
      - centor-server-4-2   

  centor-client-4-2:
    image: mrtdeh/kive
    networks:
      - cluster
    environment:
      - NAME=client-4-2
      - DC=dc4
      - PORT=4002
      - JOIN=centor-server-4-1:3000,centor-server-4-2:3002
      - ALTERNATIVE_HOST=centor-client-4-2
    depends_on:
      - centor-server-4-1   
      - centor-server-4-2  
 

  centor-client-4-3:
    image: mrtdeh/kive
    networks:
      - cluster
    environment:
      - NAME=client-4-3
      - DC=dc4
      - PORT=4003
      - JOIN=centor-server-4-1:3000,centor-server-4-2:3002
      - ALTERNATIVE_HOST=centor-client-4-3
    depends_on:
      - centor-server-4-1   
      - centor-server-4-2  

  centor-client-4-4:
    image: mrtdeh/kive
    networks:
      - cluster
    environment:
      - NAME=client-4-4
      - DC=dc4
      - PORT=4004
      - JOIN=centor-server-4-1:3000,centor-server-4-2:3002
      - ALTERNATIVE_HOST=centor-client-4-4
    depends_on:
      - centor-server-4-1   
      - centor-server-4-2  
   

networks:
  cluster:
    name: centor_network
    # Use a custom driver
    external: true
      